  version: '3.7'

  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "3306:3306"